added most popular films
CHABNDHEANEE/java-filmorate pull request #10
Opened 2023-04-27 10:04 UTC by Varnochka

добавлен функционал получения популярных фильмов с фильтрацией по году и жанру

2023-04-27 11:51 UTC, CHABNDHEANEE requested changes
Все отлично, но кажется, есть пару моментов, которые можно сделать красивее)

2023-04-27 11:51 UTC, CHABNDHEANEE commented on src/main/java/ru/yandex/practicum/filmorate/controller/LikeController.java
> +    public List<Film> getPopularFilmsByGenreAndYear(@RequestParam(name = "count", required = false) Integer limit,
Можно прописать параметр defaultValue = "10" для limit'a, тогда можно убрать required и проверку if limit == null далее

2023-04-27 11:51 UTC, CHABNDHEANEE commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/LikeDaoImpl.java
>          }
можно убрать эту проверку, если задать дефолтное значение в контроллере

2023-04-27 11:51 UTC, CHABNDHEANEE commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/LikeDaoImpl.java
> +        return jdbcTemplate.query(sql, this::makeFilm, genreId, limit);
Это все можно объединить в блок If - else if - else. По сути не обязательно, но кажется будет выглядить более структурировано

2023-05-02 11:27 UTC, CHABNDHEANEE approved these changes

2023-05-02 14:32 UTC, AssortedCaret approved these changes

2023-05-03 16:35 UTC, merged