Add remove endpoint
CHABNDHEANEE/java-filmorate pull request #14
Opened 2023-04-28 19:54 UTC by Vlad-Sharapov

Необходимо будет проверить удаление после мерджа всех веток

2023-05-01 13:59 UTC, AngelaIvleva commented on src/test/java/ru/yandex/practicum/filmorate/service/Dao/UserDaoTest.java
> +//    }
без этого закоменченного метода код будет выглядеть аккуратнее)

2023-05-02 11:33 UTC, CHABNDHEANEE requested changes
У меня замечаний нет, все отлично :) 
Нужно только убрать закоменченый код и будет апрув

2023-05-02 15:08 UTC, CHABNDHEANEE approved these changes

2023-05-03 07:36 UTC, AngelaIvleva approved these changes

2023-05-03 19:20 UTC, merged