Develop
CHABNDHEANEE/java-filmorate pull request #22
Opened 2023-05-04 16:32 UTC by CHABNDHEANEE

2023-05-04 20:17 UTC, Fleaman777 requested changes
Ребята привет.

Поздравляю вас с завершением такой масштабной работы. Вы большие молодцы.
У вас очень круто все получилось. Есть, конечно, что поправить, но ничего сверх глобального, в основном какие-то косметические моменты.
Очень понравились ваши запросы, составлены грамотно и оптимально, для самого начала карьеры - это достойный уровень. Сама логика в сервисах, тоже на отлично, так же как и контроллеры
Так держать 💪🏼

2023-05-04 20:17 UTC, Fleaman777 commented on README.md
> +добавлять в друзья других пользователей и просматривать ленту событий по активностям друзей.
функционал лучше написать в ввиде списка и использовать те названия, которые указаны в задании, 
так будет чуть проще понять, что именно реализовано в приложении

2023-05-04 20:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
много логики для метода контроллера, 
правильней будет ее расположить в сервисе, в соответствующем методе, 

метод в контроллере, по сути, только принемает реквест и передает параметры в метод сервиса, где происходят все необходимые манипуляции

2023-05-04 20:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
здесь аналагично предыдущему комментарию

2023-05-04 20:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDaoImpl.java
> +    private final ArrayList<Integer> listIdDirector = new ArrayList<>();
не совсем понимаю зачем нужен этот arrayList, 
понятно, что для сохранения айдищников режисеров, 
но просто при каждой перезагрузке приложения, этот лист будет обнулятся, а  следовательно данные, на которые может быть завязана логика будут пропадать, что может привести к потенциальным проблемам

2023-05-04 20:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FeedDaoImpl.java
> +            throw new ObjectExistenceException("User " + userId + " Not Found");
для того, что бы вставлять параметры в строку, можно использовать String.format(),
так строка будет выглядеть более цельно

2023-05-04 20:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    private final DirectorDao directorDao;
инжектить в один репозиторий, другие, не очень хорошая практика, 
т.к. в таком слуачае нарушается принцип разделения ответственности, 
в данном случае, это означает, что у 1 dao класса, должна быть связть только с 1 сущностью

попробуйте немного разрешить эту ситуацию, 
если не получится, оставте так, как выйдет, ну и конечно просто запомнить на будущее)

здесь об это более подробно
https://stackoverflow.com/questions/69999329/is-it-okay-to-autowire-multiple-repositories-into-another-repository-in-spring-d

2023-05-04 20:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +        if (userFilmsIds == null) {
это условие можно сделать чуть выше, до того, как создаете Map'ы.
в таком случае, не будут создаваться перменные, которые не успели задействовать

2023-05-04 20:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +                .collect(Collectors.toList());
это хороший стрим, 
но можно попробовать часть логики этого стрима так же сделать через стрим, 
например, может быть полезным метод стрима flatMap

2023-05-04 20:17 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/service/Dao/UserDaoTest.java
>  }
отдельный респект за тесты, 
хоть их не было в задании, но молодцы, что не поленились их написать

2023-05-06 10:44 UTC, CHABNDHEANEE commented
Возможно иисправление с инжектами получилось сильно костыльным, но других идей особо нет, если, что сделаем откат.

2023-05-07 18:01 UTC, Fleaman777 approved these changes
Все отлично.
Можно еще раз однозначно сказать, вы крутые ! :)
Получено огромное количество бесценного опыта, который обязательно пригодится.
Удачи в дальнейшем обучении, да и в целом, в новой карьере

2023-05-08 16:04 UTC, merged