Add database
CHABNDHEANEE/java-filmorate pull request #8
Opened 2023-04-12 21:56 UTC by CHABNDHEANEE

2023-04-12 21:58 UTC, CHABNDHEANEE commented
Никак не могу побороть эти тесты((( Бросит удалить бинарные файлы из PR

2023-04-13 19:55 UTC, Fleaman777 requested changes

2023-04-13 19:55 UTC, Fleaman777 commented on pom.xml
> +			<artifactId>spring-boot-starter-data-jpa</artifactId>
эта зависимость содержит много лишнего для текущего спринта, ее пока можно убрать

2023-04-13 19:55 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/auxilary/DateValidator.java
> +    String validDate;
поле должно быть private

2023-04-13 19:55 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    @ExceptionHandler
в контроллерах эксепшен хэндлеры одинаковые, их можно было бы вынести в один в общий класс

2023-04-13 19:55 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    private Film makeFilm(ResultSet rs, int rowNum) throws SQLException {
приватные методы должны идти после публичных, 
так удобней ориентироваться в классе, когда ты знаешь, что все находится на своем месте

2023-04-13 19:55 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/LikeDaoImpl.java
> +
что-то многовато пустых строк)

2023-04-13 19:55 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmDbServiceTest.java
> +}
Не совсем верные и полные тесты, 

нужно создать тесты на каждый DAO класс, и протестировать каждый публичный метод в этих DAO классах, 
а что бы тесты получились правильные, нужно использовать аннотации, да и в целом описание тестов в задании

2023-04-14 15:29 UTC, CHABNDHEANEE commented
Привет, спасибо за качественный фидбек и замечания :)

2023-04-15 13:15 UTC, Fleaman777 approved these changes

2023-04-15 13:15 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/service/Dao/UserDaoTest.java
> +        testAddUsers();
не совсем верное использование метода testAddUsers()
поскольку это тест метод, он выполняет только ожну функцию, протестировать какой-то функционал, 
а что бы просетать какие-то параметры перед запуском тестов, лучше использовать метод с аннотацеий @BeforeEach

2023-04-15 13:15 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/service/Dao/FilmDaoTest.java
> +        testAddFilm();
здесь аналагично с юзер тест

2023-04-17 18:37 UTC, merged