добавлен функционал общих фильмов
CHABNDHEANEE/java-filmorate pull request #9
Opened 2023-04-26 20:16 UTC by Varnochka

2023-04-26 20:52 UTC, CHABNDHEANEE requested changes
Все в целом, как по мне, отлично, но есть пара незначительных моментов, которые можно улучшить)

2023-04-26 20:52 UTC, CHABNDHEANEE commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDao.java
> +    List<Film> findCommonFilmsByUserIdAndFriendId(Integer userId, Integer friendId);
Предлагаю немного укоротить название, немного великовато, как по мне. Возможно будет достаточно просто findCommonFilms

2023-04-26 20:52 UTC, CHABNDHEANEE commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                                         @RequestParam(name = "friendId") Integer friendId) {
Вроде как можно убрать параметр name, ничего сломаться не должно, так как он совпадает с именем переменной

2023-04-26 20:52 UTC, CHABNDHEANEE commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmDbService.java
> +    public List<Film> getCommonFilmsBetweenUserAndFriend(Integer userId, Integer friendId) {
Тоже самое предложение по названию, кажется, можно покороче

2023-04-26 20:52 UTC, CHABNDHEANEE commented on src/test/java/ru/yandex/practicum/filmorate/service/Dao/FilmDaoTest.java
> +    void commonFilms() {
Нужно немного поднять тест, чтобы он был перед приватным методом, тк все приватные методы должны быть в конце. + было бы круто добавить модификатор доступа к нему public

2023-04-26 20:52 UTC, CHABNDHEANEE commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        List<Film> films = jdbcTemplate.query(
Вроде как смысла в этой переменной нет, кажется, можно сразу возвращать запрос

2023-04-27 07:29 UTC, AngelaIvleva commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        }
Здесь происходит валидация юзеров на существование, код дублируется, отличаются только ID юзеров - отличным вариантом было бы вынести валидацию в отдельный метод, например:

private void validateUser(int userId) {
        Integer resultSearchByUserId = jdbcTemplate
                .queryForObject("SELECT count(USER_ID) FROM USERS WHERE USER_ID = ?", Integer.class, userId);
        if (resultSearchByUserId == null || resultSearchByUserId == 0) {
            throw new ObjectExistenceException("User with id='" + userId + "' not found");
        }
    }

2023-04-27 08:11 UTC, Varnochka commented
Внесла исправления по вашим замечаниям)
Предлагаю также еще в контроллере FilmsController над классом поставить аннотацию @RequestMapping("/films") чтобы не прописывать в аннотации маппинга каждого метода "/films".

2023-04-27 08:14 UTC, CHABNDHEANEE commented
> Внесла исправления по вашим замечаниям) Предлагаю также еще в контроллере FilmsController над классом поставить аннотацию @RequestMapping("/films") чтобы не прописывать в аннотации маппинга каждого метода "/films".

Да, согласен, стоит добавить

2023-04-27 08:52 UTC, CHABNDHEANEE requested changes

2023-04-27 08:52 UTC, CHABNDHEANEE commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getCommonFilms(@RequestParam Integer userId, @RequestParam(name = "friendId") Integer friendId) {
У friendId он вроде как тоже не нужен. + согласен с предложением вынести "/films"

2023-04-27 08:52 UTC, CHABNDHEANEE commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        }
Вроде как эту часть можно убрать, так как проверка вынесена в отдельный метод, который вызывается парой строчек выше

2023-04-27 08:52 UTC, CHABNDHEANEE commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        if (result == null) {
Вроде как нужно добавить сюда проверку result == 0

2023-04-27 08:52 UTC, CHABNDHEANEE commented on src/test/java/ru/yandex/practicum/filmorate/service/Dao/FilmDaoTest.java
> +                .build());
Предлагаю создание юзеров вынести в самое начало, где создаются фильмы. Тогда и код почище станет в тесте и можно будет юзеров использовать повторно в случае добавления новых тестов

2023-04-27 10:00 UTC, Varnochka commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        if (result == null) {
т.к. у нас запрос приходит в объект Integer, то возможна при использовании только result == 0 возможна ошибка NullPointerException. тогда добавлю два условия

2023-04-27 10:07 UTC, CHABNDHEANEE approved these changes
Теперь все супер)

2023-04-27 15:12 UTC, AngelaIvleva approved these changes
класс))

2023-04-27 15:13 UTC, merged